# Generated by Django 4.2.16 on 2024-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0002_remove_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
