# Generated by Django 4.2.16 on 2024-11-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0003_remove_patient_doctor_remove_patient_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
