# Generated by Django 4.2.16 on 2024-11-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0004_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
